### ISSUE TITLE
enable dependbot

### ISSUE THREAD

**Issue by kissmannchristoph** [sergej-stk/notekeeper#3]
github has a dependbot, the dependbot scans your java project packages for updates, then it will create a pull request to update the package.

should we add that?

example: https://github.com/kissmannchristoph/Python-UI-Docker-auto-build-and-deploy/blob/main/.github/dependabot.yml
example pull request: https://github.com/kissmannchristoph/Python-UI-Docker-auto-build-and-deploy/pull/15

**Comment by kissmannchristoph** [comment]
@sergej-stk

**Comment by sergej-stk** [comment]
https://github.com/sergej-stk/notekeeper/pull/6

**Comment by sergej-stk** [comment]
https://github.com/sergej-stk/notekeeper/pull/7
